#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Загрузка исторических данных для новых 55 монет
"""

COINS_TO_DOWNLOAD = ['ADXUSDT', 'ALPHAUSDT', 'AMPUSDT', 'ANKRUSDT', 'AUCTIONUSDT', 'AUDIOUSDT', 'BAKEUSDT', 'BETAUSDT', 'BNXUSDT', 'BTTUSDT', 'CHRUSDT', 'CITYUSDT', 'COSUSDT', 'CTKUSDT', 'CVCUSDT', 'DARUSDT', 'FLMUSDT', 'FORTHUSDT', 'FTTUSDT', 'GFTUSDT', 'HNTUSDT', 'ICXUSDT', 'IOSTUSDT', 'JASMYUSDT', 'KP3RUSDT', 'KSMUSDT', 'LAZIOUSDT', 'LINAUSDT', 'LITUSDT', 'LPTUSDT', 'MOVRUSDT', 'OGNUSDT', 'OMGUSDT', 'PERPUSDT', 'PLAUSDT', 'PORTOUSDT', 'POWRUSDT', 'QIUSDT', 'RADUSDT', 'RAREUSDT', 'RENUSDT', 'RGTUSDT', 'RSRUSDT', 'RVNUSDT', 'SFPUSDT', 'SKLUSDT', 'STORJUSDT', 'SUNUSDT', 'SXPUSDT', 'TLMUSDT', 'WAVESUSDT', 'WAXPUSDT', 'XEMUSDT', 'YFIIUSDT', 'ZENUSDT']
