#!/bin/bash

echo "📋 РУЧНОЕ РАЗВЕРТЫВАНИЕ ДАШБОРДА НА СЕРВЕРЕ"
echo "=============================================="
echo ""
echo "1. Подключитесь к серверу:"
echo "   ssh root@185.177.216.15"
echo "   Пароль: u44Ww9NmtQj,XG"
echo ""
echo "2. На сервере выполните команды:"
echo "   cd /root"
echo "   mkdir -p atra"
echo "   cd atra"
echo ""
echo "3. Создайте файлы дашборда:"
echo "   nano web/dashboard.py"
echo "   nano rest_api.py"
echo "   nano deploy_dashboard.sh"
echo ""
echo "4. Запустите дашборд:"
echo "   python3 web/dashboard.py --host 0.0.0.0 --port 5002 &"
echo "   python3 rest_api.py --host 0.0.0.0 --port 8080 &"
echo ""
echo "5. Проверьте статус:"
echo "   ss -tlnp | grep -E '(5002|8080)'"
echo ""
echo "📊 После запуска дашборд будет доступен:"
echo "   http://185.177.216.15:5002"
echo "   http://185.177.216.15:8080"
