#!/usr/bin/expect -f
# Перезапуск бота и проверка работы

set timeout 120
set server "185.177.216.15"
set user "root"
set password "u44Ww9NmtQj,XG"

spawn ssh -o StrictHostKeyChecking=no $user@$server

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "# " {
        send "cd /root/atra\r"
        expect "# "
        
        send "echo '=================================================================================='\r"
        expect "# "
        send "echo '🔄 ПЕРЕЗАПУСК БОТА И ПРОВЕРКА РАБОТЫ'\r"
        expect "# "
        send "echo '=================================================================================='\r"
        expect "# "
        
        # Останавливаем бота
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 1: Остановка бота'\r"
        expect "# "
        send "systemctl stop myproject.service 2>/dev/null || true\r"
        expect "# "
        send "pkill -f 'signal_live.py' 2>/dev/null || true\r"
        expect "# "
        send "pkill -f 'main.py' 2>/dev/null || true\r"
        expect "# "
        send "sleep 3\r"
        expect "# "
        
        # Проверяем, что остановлен
        send "ps aux | grep -E '(signal_live|main\\.py)' | grep -v grep || echo '✅ Бот остановлен'\r"
        expect "# "
        
        # Запускаем бота
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 2: Запуск бота'\r"
        expect "# "
        send "cd /root/atra && nohup python3 signal_live.py > signal_live.log 2>&1 &\r"
        expect "# "
        send "sleep 5\r"
        expect "# "
        
        # Проверяем процессы
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 3: Проверка процессов'\r"
        expect "# "
        send "ps aux | grep -E '(signal_live|main\\.py)' | grep -v grep || echo '❌ Бот не запущен'\r"
        expect "# "
        
        # Проверяем логи (первые 30 строк)
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 4: Проверка логов (последние 30 строк)'\r"
        expect "# "
        send "tail -30 /root/atra/signal_live.log 2>/dev/null | tail -20\r"
        expect "# "
        
        # Проверяем конфигурацию
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 5: Проверка конфигурации фильтров'\r"
        expect "# "
        send "python3 << 'PYEOF'\r"
        expect "# "
        send "import sys\r"
        expect "# "
        send "sys.path.insert(0, '/root/atra')\r"
        expect "# "
        send "try:\r"
        expect "# "
        send "    from config import (\r"
        expect "# "
        send "        USE_VP_FILTER, USE_VWAP_FILTER, USE_ORDER_FLOW_FILTER,\r"
        expect "# "
        send "        USE_MICROSTRUCTURE_FILTER, USE_MOMENTUM_FILTER, USE_TREND_STRENGTH_FILTER,\r"
        expect "# "
        send "        USE_AMT_FILTER, USE_MARKET_PROFILE_FILTER, USE_INSTITUTIONAL_PATTERNS_FILTER\r"
        expect "# "
        send "    )\r"
        expect "# "
        send "    print('✅ Все фильтры импортированы')\r"
        expect "# "
        send "    print(f'VP Filter: {\"✅\" if USE_VP_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'VWAP Filter: {\"✅\" if USE_VWAP_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'Order Flow: {\"✅\" if USE_ORDER_FLOW_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'Microstructure: {\"✅\" if USE_MICROSTRUCTURE_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'Momentum: {\"✅\" if USE_MOMENTUM_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'Trend Strength: {\"✅\" if USE_TREND_STRENGTH_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'AMT: {\"✅\" if USE_AMT_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'Market Profile: {\"✅\" if USE_MARKET_PROFILE_FILTER else \"❌\"}')\r"
        expect "# "
        send "    print(f'Institutional Patterns: {\"✅\" if USE_INSTITUTIONAL_PATTERNS_FILTER else \"❌\"}')\r"
        expect "# "
        send "except Exception as e:\r"
        expect "# "
        send "    print(f'❌ Ошибка: {e}')\r"
        expect "# "
        send "PYEOF\r"
        expect "# "
        
        # Проверяем отбор монет
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 6: Проверка отбора монет'\r"
        expect "# "
        send "python3 << 'PYEOF'\r"
        expect "# "
        send "import sys\r"
        expect "# "
        send "sys.path.insert(0, '/root/atra')\r"
        expect "# "
        send "try:\r"
        expect "# "
        send "    from src.execution.exchange_api import get_filtered_top_usdt_pairs_fast\r"
        expect "# "
        send "    pairs = get_filtered_top_usdt_pairs_fast(limit=10)\r"
        expect "# "
        send "    if pairs:\r"
        expect "# "
        send "        print(f'✅ Найдено монет: {len(pairs)}')\r"
        expect "# "
        send "        print(f'Топ-10: {pairs[:10]}')\r"
        expect "# "
        send "    else:\r"
        expect "# "
        send "        print('⚠️  Список монет пуст')\r"
        expect "# "
        send "except Exception as e:\r"
        expect "# "
        send "    print(f'❌ Ошибка: {e}')\r"
        expect "# "
        send "PYEOF\r"
        expect "# "
        
        # Проверяем базу данных
        send "echo ''\r"
        expect "# "
        send "echo '📋 ШАГ 7: Проверка базы данных'\r"
        expect "# "
        send "python3 << 'PYEOF'\r"
        expect "# "
        send "import sqlite3\r"
        expect "# "
        send "import os\r"
        expect "# "
        send "db_path = '/root/atra/trading.db'\r"
        expect "# "
        send "if os.path.exists(db_path):\r"
        expect "# "
        send "    conn = sqlite3.connect(db_path)\r"
        expect "# "
        send "    cursor = conn.cursor()\r"
        expect "# "
        send "    cursor.execute('SELECT COUNT(*) FROM signals WHERE datetime(ts) > datetime(\\\"now\\\", \\\"-24 hours\\\")')\r"
        expect "# "
        send "    signals_24h = cursor.fetchone()[0]\r"
        expect "# "
        send "    print(f'Сигналов за 24ч: {signals_24h}')\r"
        expect "# "
        send "    cursor.execute('SELECT COUNT(*) FROM active_signals WHERE status = \\\"active\\\"')\r"
        expect "# "
        send "    active = cursor.fetchone()[0]\r"
        expect "# "
        send "    print(f'Активных сигналов: {active}')\r"
        expect "# "
        send "    cursor.execute('SELECT symbol, side, ts FROM signals ORDER BY ts DESC LIMIT 5')\r"
        expect "# "
        send "    recent = cursor.fetchall()\r"
        expect "# "
        send "    if recent:\r"
        expect "# "
        send "        print('Последние 5 сигналов:')\r"
        expect "# "
        send "        for symbol, side, ts in recent:\r"
        expect "# "
        send "            print(f'  - {symbol} {side} ({ts})')\r"
        expect "# "
        send "    conn.close()\r"
        expect "# "
        send "else:\r"
        expect "# "
        send "    print('База данных не найдена')\r"
        expect "# "
        send "PYEOF\r"
        expect "# "
        
        send "echo ''\r"
        expect "# "
        send "echo '=================================================================================='\r"
        expect "# "
        send "echo '✅ ПРОВЕРКА ЗАВЕРШЕНА'\r"
        expect "# "
        send "echo '=================================================================================='\r"
        expect "# "
        
        send "exit\r"
        expect eof
    }
    timeout {
        puts "Timeout"
        exit 1
    }
}

wait

