#!/usr/bin/expect -f
set timeout 60
set server "185.177.216.15"
set user "root"
set password "u44Ww9NmtQj,XG"

spawn ssh -o StrictHostKeyChecking=no $user@$server

expect {
    "password:" { send "$password\r"; exp_continue }
    "yes/no" { send "yes\r"; exp_continue }
    "# " {
        send "cd /root/atra\r"
        expect "# "
        send "python3 << 'PYEOF'\r"
        send "import sqlite3\r"
        send "import shutil\r"
        send "import os\r"
        send "from datetime import datetime\r"
        send "db_path = '/root/atra/trading.db'\r"
        send "backup_dir = '/root/atra/backups'\r"
        send "os.makedirs(backup_dir, exist_ok=True)\r"
        send "print('🔧 ВОССТАНОВЛЕНИЕ БАЗЫ ДАННЫХ')\r"
        send "print('=' * 80)\r"
        send "if not os.path.exists(db_path):\r"
        send "    print('❌ БД не найдена, создаем новую...')\r"
        send "    conn = sqlite3.connect(db_path)\r"
        send "    cursor = conn.cursor()\r"
        send "    cursor.execute('CREATE TABLE IF NOT EXISTS signals (id INTEGER PRIMARY KEY, symbol TEXT, signal_type TEXT, entry_price REAL, status TEXT DEFAULT \\'active\\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)')\r"
        send "    cursor.execute('CREATE TABLE IF NOT EXISTS active_signals (id INTEGER PRIMARY KEY, symbol TEXT, signal_type TEXT, entry_price REAL, status TEXT DEFAULT \\'active\\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)')\r"
        send "    cursor.execute('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, user_id TEXT UNIQUE, username TEXT, is_active BOOLEAN DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)')\r"
        send "    conn.commit()\r"
        send "    conn.close()\r"
        send "    print('✅ Новая БД создана')\r"
        send "else:\r"
        send "    print('📦 Создание бэкапа...')\r"
        send "    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')\r"
        send "    backup_path = os.path.join(backup_dir, f'trading_db_backup_{timestamp}.db')\r"
        send "    shutil.copy2(db_path, backup_path)\r"
        send "    print(f'✅ Бэкап создан: {backup_path}')\r"
        send "    print('🔍 Проверка целостности...')\r"
        send "    try:\r"
        send "        conn = sqlite3.connect(db_path)\r"
        send "        cursor = conn.cursor()\r"
        send "        cursor.execute('PRAGMA integrity_check')\r"
        send "        result = cursor.fetchone()\r"
        send "        conn.close()\r"
        send "        if result and result[0] == 'ok':\r"
        send "            print('✅ База данных целостна')\r"
        send "        else:\r"
        send "            print(f'❌ БД повреждена: {result}')\r"
        send "            print('🔧 Попытка восстановления...')\r"
        send "            recovered_path = db_path + '.recovered'\r"
        send "            try:\r"
        send "                conn = sqlite3.connect(db_path)\r"
        send "                recovered_conn = sqlite3.connect(recovered_path)\r"
        send "                conn.backup(recovered_conn)\r"
        send "                conn.close()\r"
        send "                recovered_conn.close()\r"
        send "                test_conn = sqlite3.connect(recovered_path)\r"
        send "                test_cursor = test_conn.cursor()\r"
        send "                test_cursor.execute('PRAGMA integrity_check')\r"
        send "                test_result = test_cursor.fetchone()\r"
        send "                test_conn.close()\r"
        send "                if test_result and test_result[0] == 'ok':\r"
        send "                    shutil.move(recovered_path, db_path)\r"
        send "                    print('✅ БД восстановлена')\r"
        send "                else:\r"
        send "                    os.remove(recovered_path)\r"
        send "                    print('❌ Восстановление не удалось, пересоздаем структуру...')\r"
        send "                    os.remove(db_path)\r"
        send "                    new_conn = sqlite3.connect(db_path)\r"
        send "                    new_cursor = new_conn.cursor()\r"
        send "                    new_cursor.execute('CREATE TABLE IF NOT EXISTS signals (id INTEGER PRIMARY KEY, symbol TEXT, signal_type TEXT, entry_price REAL, status TEXT DEFAULT \\'active\\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)')\r"
        send "                    new_cursor.execute('CREATE TABLE IF NOT EXISTS active_signals (id INTEGER PRIMARY KEY, symbol TEXT, signal_type TEXT, entry_price REAL, status TEXT DEFAULT \\'active\\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)')\r"
        send "                    new_cursor.execute('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, user_id TEXT UNIQUE, username TEXT, is_active BOOLEAN DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)')\r"
        send "                    new_conn.commit()\r"
        send "                    new_conn.close()\r"
        send "                    print('✅ Структура пересоздана')\r"
        send "            except Exception as e:\r"
        send "                print(f'❌ Ошибка восстановления: {e}')\r"
        send "                if os.path.exists(recovered_path):\r"
        send "                    os.remove(recovered_path)\r"
        send "    except Exception as e:\r"
        send "        print(f'❌ Ошибка: {e}')\r"
        send "    print('🔍 Финальная проверка...')\r"
        send "    try:\r"
        send "        conn = sqlite3.connect(db_path)\r"
        send "        cursor = conn.cursor()\r"
        send "        cursor.execute('PRAGMA integrity_check')\r"
        send "        result = cursor.fetchone()\r"
        send "        if result and result[0] == 'ok':\r"
        send "            print('✅ БД целостна и готова к работе')\r"
        send "            cursor.execute('SELECT name FROM sqlite_master WHERE type=\\'table\\'')\r"
        send "            tables = cursor.fetchall()\r"
        send "            print(f'📊 Таблиц: {len(tables)}')\r"
        send "        else:\r"
        send "            print(f'❌ БД все еще повреждена')\r"
        send "        conn.close()\r"
        send "    except Exception as e:\r"
        send "        print(f'❌ Ошибка: {e}')\r"
        send "PYEOF\r"
        expect "# "
        send "exit\r"
        expect eof
    }
    timeout { puts "Timeout"; exit 1 }
}
wait
