ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'medium';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS domain_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS estimated_duration_minutes INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_duration_minutes INTEGER;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS is_department_lead BOOLEAN DEFAULT FALSE;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS department VARCHAR(255);
