[databases]
knowledge_os = host=knowledge_postgres port=5432 dbname=knowledge_os application_name=pgbouncer_backend

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432

auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1
auth_dbname = knowledge_os

pool_mode = transaction
max_client_conn = 1000

; Увеличиваем пул для снижения нагрузки на создание соединений
default_pool_size = 50
min_pool_size = 10
reserve_pool_size = 10
reserve_pool_timeout = 3

; Оптимизация переиспользования и сброса
server_reset_query = DISCARD ALL
server_check_query = SELECT 1
server_check_delay = 30

; Закрывать idle server-соединения через 10 мин (было 5)
server_idle_timeout = 600

log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
stats_period = 60
